name: Feature Request
description: Suggest a new feature or enhancement for PlanLyst
title: "[Feature] "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to improve PlanLyst? Let us know!
  - type: textarea
    id: feature
    attributes:
      label: 💡 Describe the feature
      description: What would you like to see added or improved?
      placeholder: For example: Add dark mode toggle in settings
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 🧠 Why is this feature useful?
      description: Explain the benefit or use case
      placeholder: Helps reduce eye strain when using app at night
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered (optional)
      description: Have you thought of other ways to solve this?
  - type: textarea
    id: notes
    attributes:
      label: ✍️ Additional Notes (optional)